# 1. Cargar Datos  

In [3]:
pip install -r requirements.txt

In [4]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('darkgrid')

In [5]:
df = pd.read_csv("./data/IMDB Dataset.csv")

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB


In [6]:
df.sample(5)

,review,sentiment
39853,Another period piece for Chen Kiage... (can't ...,positive
8548,"The first film was a nice one, but it is not a...",positive
20520,Others have harped here about James Stewart's ...,positive
10283,"""2001: A Space Odyssey"" is set in 2001 and the...",positive
5382,Wow! A Danish movie with this kind of content?...,positive


In [8]:
df.sentiment.value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

# 2. Reducir el Dataset

In [9]:
df_pos = df[df['sentiment']=='positive'][:5000]
df_neg = df[df['sentiment']=='negative'][:5000]

df_reviews = pd.concat([df_pos, df_neg ])

In [10]:
from sklearn.model_selection import train_test_split


# 3. Separar datos de entrenamiento y prueba

In [33]:
train,test = train_test_split(df_reviews,test_size =0.33,random_state=42)
train_x, train_y = train['review'], train['sentiment']
test_x, test_y = test['review'], test['sentiment']

In [34]:
train,test = train_test_split(df_reviews,test_size =0.33,random_state=42)

In [35]:
train_x, train_y = train['review'], train['sentiment']
test_x, test_y = test['review'], test['sentiment']

In [36]:
train_y.value_counts()

sentiment
negative    3378
positive    3322
Name: count, dtype: int64

In [54]:
train, test = train_test_split(
    df_reviews,
    test_size=0.33,
    random_state=42
)

train_x = train["review"]
train_y = train["sentiment"]

test_x = test["review"]
test_y = test["sentiment"]

print("\nTamaño de entrenamiento:")
print(train_x.shape)

print("\nTamaño de prueba:")
print(test_x.shape)


Tamaño de entrenamiento:
(6700,)

Tamaño de prueba:
(3300,)


# 4.Convertir texto a números con TF-IDF

In [37]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [38]:
tfidf = TfidfVectorizer(stop_words='english')
train_x_vector = tfidf.fit_transform(train_x)
test_x_vector = tfidf.transform(test_x)

In [39]:
train_x.shape

(6700,)

In [40]:
train_x_vector.shape

(6700, 44107)

In [41]:
type(train_x_vector)

scipy.sparse._csr.csr_matrix

In [42]:
primera_resenia = pd.DataFrame.sparse.from_spmatrix(train_x_vector,
                                  index=train_x.index,
                                  columns=tfidf.get_feature_names_out())

In [43]:
primera_resenia

,00,000,007,00am,00s,01,01pm,02,04,05,...,émigré,émigrés,était,étc,être,ísnt,île,önsjön,über,überwoman
6746,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
54,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8499,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7869,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3725,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1501,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
358,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
761,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1685,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


In [44]:
train_x.iloc[0]

"I happened to rent this movie with my sister in hopes of watching a great entertaining movie, that was humorous, however my expectations were let down. This movie was beyond disgusting and revolting for a PG-13 movie, this should have been rated R for the many mature references that went on in this movie. I wouldn't recommend allowing a 13 year old teen see this.<br /><br />Even if no one under the age of 17 is watching this movie, beware of a truly stupid movie, there's no humor in the movie, just a bunch of disgusting sexual references including a small touch of pedophilia, something that shouldn't even be joked about. <br /><br />I would like to know what happened to PG-13 movies, that were actually safe for actual a 13 year old? This is beyond a deplorable movie and should be re-rated."

In [45]:
primera_resenia = pd.DataFrame.sparse.from_spmatrix(train_x_vector,
                                  index=train_x.index,
                                  columns=tfidf.get_feature_names_out()).iloc[0]
primera_resenia

00           0
000          0
007          0
00am         0
00s          0
            ..
ísnt         0
île          0
önsjön       0
über         0
überwoman    0
Name: 6746, Length: 44107, dtype: Sparse[float64, 0]

In [46]:
primera_resenia[primera_resenia != 0]

13               0.45849
17               0.12824
actual          0.091601
actually        0.061461
age             0.088765
allowing         0.12824
beware          0.143046
br              0.124945
bunch           0.093128
deplorable      0.168137
disgusting      0.237945
entertaining    0.081088
expectations    0.103149
great           0.048868
happened        0.176853
hopes           0.114028
humor           0.084465
humorous        0.116516
including       0.087603
joked           0.168137
just            0.037675
know            0.053984
let              0.07195
like            0.036454
mature          0.126021
movie           0.276309
movies            0.0522
old             0.123513
pedophilia      0.172712
pg              0.260154
rated           0.206643
recommend       0.076198
references      0.226901
rent            0.093234
revolting       0.151971
safe            0.119732
sexual          0.098677
shouldn         0.108203
sister          0.095008
small           0.078916


In [47]:
from sklearn.svm import SVC
svc = SVC(kernel='linear')
svc.fit(train_x_vector, train_y)

,C,1.0
,kernel,'linear'
,degree,3
,gamma,'scale'
,coef0,0.0
,shrinking,True
,probability,False
,tol,0.001
,cache_size,200
,class_weight,None
,verbose,False


In [48]:
print(svc.predict(tfidf.transform(['A good movie'])))
print(svc.predict(tfidf.transform(['An excellent movie'])))
print(svc.predict(tfidf.transform(['I did not like this movie at all I gave this movie away'])))

['positive']
['positive']
['negative']


In [49]:
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [50]:
print(svc.score(test_x_vector, test_y))

0.8706060606060606


In [51]:
from sklearn.metrics import f1_score

f1_score(test_y,svc.predict(test_x_vector),
          labels = ['positive','negative'],average=None)

array([0.87400413, 0.86701962])

In [52]:
from sklearn.metrics import classification_report

print(classification_report(test_y,
                            svc.predict(test_x_vector),
                            labels = ['positive','negative']))

              precision    recall  f1-score   support

    positive       0.87      0.88      0.87      1678
    negative       0.88      0.86      0.87      1622

    accuracy                           0.87      3300
   macro avg       0.87      0.87      0.87      3300
weighted avg       0.87      0.87      0.87      3300



In [53]:
from sklearn.metrics import confusion_matrix

conf_mat = confusion_matrix(test_y,
                           svc.predict(test_x_vector),
                           labels = ['positive', 'negative'])
conf_mat

array([[1481,  197],
       [ 230, 1392]])

In [55]:
tfidf = TfidfVectorizer(
    stop_words="english",
    max_features=5000
)

train_x_vector = tfidf.fit_transform(train_x)
test_x_vector = tfidf.transform(test_x)

print("\nForma de la matriz de entrenamiento:")
print(train_x_vector.shape)

print("\nForma de la matriz de prueba:")
print(test_x_vector.shape)


Forma de la matriz de entrenamiento:
(6700, 5000)

Forma de la matriz de prueba:
(3300, 5000)


# 5. Crear los Modelos

In [64]:
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix

In [ ]:
# 5. Definir los modelos a evaluar
modelos = {
    "SVM": SVC(kernel="linear"),
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "GaussianNB": GaussianNB(),
    "Decision Tree": DecisionTreeClassifier(random_state=42)
}

In [ ]:
# 6. Entrenar y evaluar cada modelo

resultados = []

for nombre, modelo in modelos.items():

    print("\n==========================================")
    print(f"Modelo: {nombre}")
    print("==========================================")

    # GaussianNB necesita matrices densas.
    # Los demás modelos pueden trabajar con matrices dispersas.
    if nombre == "GaussianNB":
        modelo.fit(train_x_vector.toarray(), train_y)
        predicciones = modelo.predict(test_x_vector.toarray())
    else:
        modelo.fit(train_x_vector, train_y)
        predicciones = modelo.predict(test_x_vector)

    accuracy = accuracy_score(test_y, predicciones)
    f1_positivo = f1_score(
        test_y,
        predicciones,
        pos_label="positive"
    )
    f1_negativo = f1_score(
        test_y,
        predicciones,
        pos_label="negative"
    )

    resultados.append({
        "Modelo": nombre,
        "Accuracy": accuracy,
        "F1 positivo": f1_positivo,
        "F1 negativo": f1_negativo
    })

    print("\nAccuracy:")
    print(accuracy)

    print("\nF1 positivo:")
    print(f1_positivo)

    print("\nF1 negativo:")
    print(f1_negativo)

    print("\nReporte de clasificación:")
    print(classification_report(test_y, predicciones))

    print("\nMatriz de confusión:")
    print(confusion_matrix(
        test_y,
        predicciones,
        labels=["positive", "negative"]
    ))


Modelo: SVM

Accuracy:
0.8693939393939394

F1 positivo:
0.8721447641649362

F1 negativo:
0.8665221430783524

Reporte de clasificación:
              precision    recall  f1-score   support

    negative       0.87      0.86      0.87      1622
    positive       0.87      0.88      0.87      1678

    accuracy                           0.87      3300
   macro avg       0.87      0.87      0.87      3300
weighted avg       0.87      0.87      0.87      3300


Matriz de confusión:
[[1470  208]
 [ 223 1399]]

Modelo: Logistic Regression

Accuracy:
0.8706060606060606

F1 positivo:
0.8734064630892381

F1 negativo:
0.8676789587852495

Reporte de clasificación:
              precision    recall  f1-score   support

    negative       0.87      0.86      0.87      1622
    positive       0.87      0.88      0.87      1678

    accuracy                           0.87      3300
   macro avg       0.87      0.87      0.87      3300
weighted avg       0.87      0.87      0.87      3300


Matriz d

In [ ]:
#Comparar resultados de los modelos
df_resultados = pd.DataFrame(resultados)

print("\n==========================================")
print("Comparación final de modelos")
print("==========================================")
print(df_resultados)

mejor_modelo = df_resultados.sort_values(
    by="Accuracy",
    ascending=False
).iloc[0]

print("\nMejor modelo según Accuracy:")
print(mejor_modelo)


Comparación final de modelos
                Modelo  Accuracy  F1 positivo  F1 negativo
0                  SVM  0.869394     0.872145     0.866522
1  Logistic Regression  0.870606     0.873406     0.867679
2           GaussianNB  0.771212     0.768192     0.774155
3        Decision Tree  0.714242     0.722402     0.705589

Mejor modelo según Accuracy:
Modelo         Logistic Regression
Accuracy                  0.870606
F1 positivo               0.873406
F1 negativo               0.867679
Name: 1, dtype: object


In [ ]:
# Comparar resultados de los modelos SVM vs Logistic Regression
from IPython.display import display
import pandas as pd

frases = [
    "A good movie",
    "An excellent movie",
    "I did not like this movie at all",
    "This movie was boring and terrible",
    "I loved the story and the acting was great"
]

# Vectorizar frases nuevas
frases_vector = tfidf.transform(frases)

# Entrenar modelo SVM
modelo_svm = SVC(kernel="linear")
modelo_svm.fit(train_x_vector, train_y)

# Entrenar modelo Logistic Regression
modelo_logistic = LogisticRegression(max_iter=1000)
modelo_logistic.fit(train_x_vector, train_y)

# Predicciones
predicciones_svm = modelo_svm.predict(frases_vector)
predicciones_logistic = modelo_logistic.predict(frases_vector)

# Crear tabla comparativa
tabla_predicciones = pd.DataFrame({
    "Frase": frases,
    "Predicción SVM": predicciones_svm,
    "Predicción Logistic Regression": predicciones_logistic
})

print("\n==========================================")
print("Comparación de predicciones por modelo")
print("==========================================")
display(tabla_predicciones)


Comparación de predicciones por modelo


,Frase,Predicción SVM,Predicción Logistic Regression
0,A good movie,positive,positive
1,An excellent movie,positive,positive
2,I did not like this movie at all,negative,negative
3,This movie was boring and terrible,negative,negative
4,I loved the story and the acting was great,positive,positive


# CONCLUSION

Después de entrenar y evaluar los modelos SVM, Logistic Regression, GaussianNB y Decision Tree, se observó que el modelo con mejor desempeño fue Logistic Regression, con un accuracy de 0.870606. Este resultado fue ligeramente superior al obtenido por SVM, que alcanzó un accuracy de 0.869394.

Aunque la diferencia entre Logistic Regression y SVM fue pequeña, Logistic Regression obtuvo el mejor resultado general y también presentó un F1-score positivo de 0.873406 y un F1-score negativo de 0.867679. Esto indica que el modelo logró clasificar de manera equilibrada tanto reseñas positivas como negativas.

Por otro lado, GaussianNB obtuvo un rendimiento menor, con un accuracy de 0.771212, mientras que Decision Tree fue el modelo con el desempeño más bajo, con un accuracy de 0.714242. Esto sugiere que estos modelos no fueron tan adecuados para este problema de clasificación de texto usando TF-IDF.

Asì, aunque SVM era una buena opción inicial para el análisis de sentimientos, en esta prueba Logistic Regression fue el mejor modelo, ya que obtuvo el accuracy más alto y mantuvo un buen equilibrio entre las métricas de ambas clases. Por esta razón, se seleccionó Logistic Regression como el modelo final para realizar predicciones con nuevas reseñas.

Por último, para comprobar el comportamiento de los dos mejores modelos, se probaron varias frases nuevas con SVM y Logistic Regression. Los resultados se organizaron en una tabla comparativa, donde se muestra la predicción realizada por cada modelo para la misma frase.

Esta comparación permite observar si ambos modelos clasifican las reseñas de manera similar o si existen diferencias en sus predicciones. En este caso, como Logistic Regression obtuvo el mejor accuracy general, sus predicciones se consideran las más confiables dentro de los modelos evaluados.